version: "3.9"

services:

  booking-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: booking-db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: booking_db
      DATABASE_PORT: 5432
      PORT: 8080
    links:
      - booking-db
    depends_on:
      - booking-db

  booking-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./postgres-init-files:/docker-entrypoint-initdb.d