server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:booking_db}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm